# Auto-generated by compose2nix.

{ pkgs, lib, config, ... }:

{
  # Runtime
  virtualisation.podman = {
    enable = true;
    autoPrune.enable = true;
    dockerCompat = true;
  };

  # Enable container name DNS for all Podman networks.
  networking.firewall.interfaces = let
    matchAll = if !config.networking.nftables.enable then "podman+" else "podman*";
  in {
    "${matchAll}".allowedUDPPorts = [ 53 ];
  };

  virtualisation.oci-containers.backend = "podman";

  # Containers
  virtualisation.oci-containers.containers."byparr" = {
    image = "ghcr.io/thephaseless/byparr:latest";
    ports = [
      "8191:8191/tcp"
    ];
    log-driver = "journald";
    extraOptions = [
      "--network-alias=byparr"
      "--network=byparr_default"
    ];
  };
  systemd.services."podman-byparr" = {
    serviceConfig = {
      Restart = lib.mkOverride 90 "always";
    };
    after = [
      "podman-network-byparr_default.service"
    ];
    requires = [
      "podman-network-byparr_default.service"
    ];
    partOf = [
      "podman-compose-byparr-root.target"
    ];
    wantedBy = [
      "podman-compose-byparr-root.target"
    ];
  };

  # Networks
  systemd.services."podman-network-byparr_default" = {
    path = [ pkgs.podman ];
    serviceConfig = {
      Type = "oneshot";
      RemainAfterExit = true;
      ExecStop = "podman network rm -f byparr_default";
    };
    script = ''
      podman network inspect byparr_default || podman network create byparr_default
    '';
    partOf = [ "podman-compose-byparr-root.target" ];
    wantedBy = [ "podman-compose-byparr-root.target" ];
  };

  # Builds
  systemd.services."podman-build-byparr-byparr" = {
    path = [ pkgs.podman pkgs.git ];
    serviceConfig = {
      Type = "oneshot";
      TimeoutSec = 300;
    };
    script = ''
      cd /home/goose/gooselab
      podman build -t ghcr.io/thephaseless/byparr:latest .
    '';
  };

  # Root service
  # When started, this will automatically create all resources and start
  # the containers. When stopped, this will teardown all resources.
  systemd.targets."podman-compose-byparr-root" = {
    unitConfig = {
      Description = "Root target generated by compose2nix.";
    };
    wantedBy = [ "multi-user.target" ];
  };
}
